# Generated by Django 4.1.7 on 2023-03-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available_dates',
        ),
        migrations.DeleteModel(
            name='AvailableDate',
        ),
        migrations.AddField(
            model_name='listing',
            name='available_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
